apiVersion: v1
kind: Service
metadata:
  name: logistics-management
  labels:
    app: logistics-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: logistics-management