---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  labels:
    app: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: username/order-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-management
  labels:
    app: production-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production-management
  template:
    metadata:
      labels:
        app: production-management
    spec:
      containers:
        - name: production-management
          image: username/production-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-management
  labels:
    app: logistics-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics-management
  template:
    metadata:
      labels:
        app: logistics-management
    spec:
      containers:
        - name: logistics-management
          image: username/logistics-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-management
  labels:
    app: sales-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales-management
  template:
    metadata:
      labels:
        app: sales-management
    spec:
      containers:
        - name: sales-management
          image: username/sales-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: order-management
  labels:
    app: order-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-management


---


apiVersion: v1
kind: Service
metadata:
  name: production-management
  labels:
    app: production-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: production-management


---


apiVersion: v1
kind: Service
metadata:
  name: logistics-management
  labels:
    app: logistics-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: logistics-management


---


apiVersion: v1
kind: Service
metadata:
  name: sales-management
  labels:
    app: sales-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sales-management

