apiVersion: v1
kind: Service
metadata:
  name: production-management
  labels:
    app: production-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: production-management